/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastral_system;

import GetSet.Variables;
import SQL.ConexionPostgreSQL;
import SQL.CrudSQL;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;


/**
 *
 * @author VzWhite
 */
public class Crud_Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form Crud_Tecnico
     */
    public Crud_Tecnico() {
        initComponents();
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        btnrealizar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFecha_nacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstado_Civil = new javax.swing.JTextField();
        txtNumero_Servicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFecha_Contrato = new javax.swing.JTextField();
        txtPago_Mensual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPago_Anual = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD TABLA MAESTRA TECNICO");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Email:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Celular:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insertar", "Consulta Especifica", "Consulta General" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        btnrealizar.setText("Realizar");
        btnrealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealizarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Nacimiento:");

        txtFecha_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha_nacimientoActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado Civil:");

        jLabel10.setText("Numero de Servicio:");

        jLabel11.setText("Fecha Contrato:");

        jLabel12.setText("Pago Mensual:");

        jLabel13.setText("Pago Anual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefono)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtPago_Anual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtPago_Mensual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnrealizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtEstado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnrealizar)
                            .addComponent(txtNumero_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnmodificar)
                            .addComponent(txtFecha_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btneliminar)
                            .addComponent(txtPago_Mensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPago_Anual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    CrudSQL objcrud = new CrudSQL();
    Variables var = new Variables();
    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        switch (combo.getSelectedItem().toString()) {
            case "Insertar":
            txtCedula.setEnabled(true);
            txtNombre.setText("");
            txtApellido.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
            txtCelular.setText("");
            
            
            txtCedula.setEnabled(true);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtEmail.setEnabled(true);
            txtTelefono.setEnabled(true);
            txtCelular.setEnabled(true);
            txtFecha_nacimiento.setEnabled(true);
            txtEstado_Civil.setEnabled(true);
            txtNumero_Servicio.setEnabled(true);
            txtFecha_Contrato.setEnabled(true);
            txtPago_Mensual.setEnabled(true);
            txtPago_Anual.setEnabled(true);
            btneliminar.setVisible(true);
            btnmodificar.setVisible(true);
            break;
            case "Consulta Especifica":
            txtCedula.setEnabled(true);
            txtNombre.setText("");
            txtApellido.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
            txtCelular.setText("");
            txtFecha_nacimiento.setText("");
            txtEstado_Civil.setText("");
            txtNumero_Servicio.setText("");
            txtFecha_Contrato.setText("");
            txtPago_Mensual.setText("");
            txtPago_Anual.setText("");
            txtNombre.setEnabled(false);
            txtApellido.setEnabled(false);
            txtEmail.setEnabled(false);
            txtTelefono.setEnabled(false);
            txtCelular.setEnabled(false);
            txtFecha_nacimiento.setEnabled(false);
            txtEstado_Civil.setEnabled(false);
            txtNumero_Servicio.setEnabled(false);
            txtFecha_Contrato.setEnabled(false);
            txtPago_Mensual.setEnabled(false);
            txtPago_Anual.setEnabled(false);
            break;
            case "Consulta General":
            txtCedula.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
            txtCelular.setText("");
            txtFecha_nacimiento.setText("");
            txtEstado_Civil.setText("");
            txtNumero_Servicio.setText("");
            txtFecha_Contrato.setText("");
            txtPago_Mensual.setText("");
            txtPago_Anual.setText("");
            
            txtCedula.setEnabled(false);
            txtNombre.setEnabled(false);
            txtApellido.setEnabled(false);
            txtEmail.setEnabled(false);
            txtTelefono.setEnabled(false);
            txtCelular.setEnabled(false);
            txtFecha_nacimiento.setEnabled(false);
            txtEstado_Civil.setEnabled(false);
            txtNumero_Servicio.setEnabled(false);
            txtFecha_Contrato.setEnabled(false);
            txtPago_Mensual.setEnabled(false);
            txtPago_Anual.setEnabled(false);
            btnmodificar.setVisible(false);
            btneliminar.setVisible(false);
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_comboActionPerformed

    private void btnrealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizarActionPerformed
        switch (combo.getSelectedItem().toString()) {
            case "Insertar":
                objcrud.insertarTecnico(txtNombre.getText(), txtApellido.getText(),txtCedula.getText(), txtEmail.getText(), txtTelefono.getText(), txtCelular.getText(), txtFecha_nacimiento.getText(), txtEstado_Civil.getText(), txtNumero_Servicio.getText(), txtFecha_Contrato.getText(), txtPago_Mensual.getText(), txtPago_Anual.getText());
            break;
            case "Consulta Especifica":
            btneliminar.setVisible(true);
            btnmodificar.setVisible(true);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtEmail.setEnabled(true);
            txtTelefono.setEnabled(true);
            txtCelular.setEnabled(true);
            txtFecha_nacimiento.setEnabled(true);
            txtEstado_Civil.setEnabled(true);
            txtNumero_Servicio.setEnabled(true);
            txtFecha_Contrato.setEnabled(true);
            txtPago_Mensual.setEnabled(true);
            txtPago_Anual.setEnabled(true);
            
            objcrud.consultaIdTecnico(txtCedula.getText());
            txtCedula.setText(var.getDoc_ident_persona());
            txtNombre.setText(var.getNombre_persona());
            txtApellido.setText(var.getApellido_persona());
            txtEmail.setText(var.getEmail_persona());
            txtTelefono.setText(var.getTelefono_persona());
            txtCelular.setText(var.getCelular_persona());
            txtFecha_nacimiento.setText(var.getFecha_nac_persona());
            txtEstado_Civil.setText(var.getEst_civil_persona());
            txtNumero_Servicio.setText(var.getId_serv_tecnico());
            txtFecha_Contrato.setText(var.getFecha_cont_tecnico());
            txtPago_Mensual.setText(var.getPago_mensual());
            txtPago_Anual.setText(var.getPago_anual());
            
            break;
            case "Consulta General":
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("Cedula");
            modelo.addColumn("Nombres");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Email");
            modelo.addColumn("Telefono");
            modelo.addColumn("Celular");
            modelo.addColumn("Fecha Nacimiento");
            modelo.addColumn("Estado Civil");
            modelo.addColumn("Numero Servicio");
            modelo.addColumn("Fecha Contrato");
            modelo.addColumn("Pago Mensual");
            modelo.addColumn("Pago Anual");

            tb.setModel(modelo);
            String datos[]= new String[50];
            ConexionPostgreSQL con = new ConexionPostgreSQL();
            try {
                Connection conexion =con.Conectar();
                java.sql.Statement st = conexion.createStatement();
                String sql="Select * from tecnico";
                ResultSet rs=st.executeQuery(sql);
                while (rs.next())
                {
                    datos[0]=rs.getString("doc_ident_persona");
                    datos[1]=rs.getString("nombre_persona");
                    datos[2]=rs.getString("apellido_persona");
                    datos[3]=rs.getString("email_persona");
                    datos[4]=rs.getString("telefono_persona");
                    datos[5]=rs.getString("celular_persona");
                    datos[6]=rs.getString("fecha_nac_persona");
                    datos[7]=rs.getString("est_civil_persona");
                    datos[8]=rs.getString("id_serv_tecnico");
                    datos[9]=rs.getString("fecha_cont_tecnico");
                    datos[10]=rs.getString("pago_mensual");
                    datos[11]=rs.getString("pago_anual");
                    modelo.addRow(datos);
                }
                rs.close();
                conexion.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el sistema de busqueda:"+ e,"Error buscqueda",JOptionPane.ERROR_MESSAGE);
            }
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_btnrealizarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        CrudSQL objcrud=new CrudSQL();
        Variables var=new Variables();
        var.setDoc_ident_persona(txtCedula.getText());
        var.setNombre_persona(txtNombre.getText());
        var.setApellido_persona(txtApellido.getText());
        var.setEmail_persona(txtEmail.getText());
        var.setTelefono_persona(txtTelefono.getText());
        var.setCelular_persona(txtCelular.getText());
        var.setFecha_nac_persona(txtFecha_nacimiento.getText());
        var.setEst_civil_persona(txtEstado_Civil.getText());
        var.setId_serv_tecnico(txtNumero_Servicio.getText());
        var.setFecha_cont_tecnico(txtFecha_Contrato.getText());
        var.setPago_mensual(txtPago_Mensual.getText());
        var.setPago_anual(txtPago_Anual.getText());

        objcrud.modificarTecnico(var.getNombre_persona(), var.getApellido_persona(), var.getDoc_ident_persona(), var.getEmail_persona(), var.getTelefono_persona(), var.getCelular_persona(), var.getFecha_nac_persona(), var.getEst_civil_persona(), var.getId_serv_tecnico(), var.getFecha_cont_tecnico(), var.getPago_mensual(), var.getPago_anual());
        txtCedula.setEnabled(true);
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        txtFecha_nacimiento.setText("");
        txtEstado_Civil.setText("");
        txtNumero_Servicio.setText("");
        txtFecha_Contrato.setText("");
        txtPago_Mensual.setText("");
        txtPago_Anual.setText("");
        
        
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtCelular.setEnabled(false);
        txtFecha_nacimiento.setEnabled(false);
        txtEstado_Civil.setEnabled(false);
        txtNumero_Servicio.setEnabled(false);
        txtFecha_Contrato.setEnabled(false);
        txtPago_Mensual.setEnabled(false);
        txtPago_Anual.setEnabled(false);
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        CrudSQL objcrud=new CrudSQL();
        Variables var=new Variables();
        objcrud.eliminarTecnico(var.getDoc_ident_persona());
        txtCedula.setEnabled(true);
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        txtFecha_nacimiento.setText("");
        txtEstado_Civil.setText("");
        txtNumero_Servicio.setText("");
        txtFecha_Contrato.setText("");
        txtPago_Mensual.setText("");
        txtPago_Anual.setText("");
        
        
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtCelular.setEnabled(false);
        txtFecha_nacimiento.setEnabled(false);
        txtEstado_Civil.setEnabled(false);
        txtNumero_Servicio.setEnabled(false);
        txtFecha_Contrato.setEnabled(false);
        txtPago_Mensual.setEnabled(false);
        txtPago_Anual.setEnabled(false);
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Index abrir= new Index();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFecha_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha_nacimientoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnrealizar;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado_Civil;
    private javax.swing.JTextField txtFecha_Contrato;
    private javax.swing.JTextField txtFecha_nacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero_Servicio;
    private javax.swing.JTextField txtPago_Anual;
    private javax.swing.JTextField txtPago_Mensual;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
