/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastral_system;

import GetSet.Variables;
import SQL.ConexionPostgreSQL;
import SQL.CrudSQL;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;



/**
 *
 * @author VzWhite
 */
public class Crud_Notaria extends javax.swing.JFrame {

    /**
     * Creates new form Crud_Notario
     */
    public Crud_Notaria() {
        initComponents();
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtRepresentante = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtSitio_referencia_not = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        btnrealizar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD TABLA MAESTRA NOTARIA");

        jLabel3.setText("Nombre:");

        jLabel2.setText("Numero:");

        jLabel4.setText("Representante:");

        jLabel5.setText("Dirección");

        jLabel6.setText("Sitio de referencia");

        jLabel7.setText("Telefono:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtSitio_referencia_not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSitio_referencia_notActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insertar", "Consulta Especifica", "Consulta General" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        btnrealizar.setText("Realizar");
        btnrealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealizarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumero)
                                    .addComponent(txtNombre)
                                    .addComponent(txtRepresentante)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtSitio_referencia_not)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnrealizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSitio_referencia_not, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnrealizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnmodificar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    CrudSQL objcrud=new CrudSQL();
    Variables var=new Variables();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Index abrir= new Index();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        switch (combo.getSelectedItem().toString()) {
            case "Insertar":
            txtNumero.setEnabled(true);
            txtNombre.setText("");
            txtRepresentante.setText("");
            txtDireccion.setText("");
            txtSitio_referencia_not.setText("");
            txtTelefono.setText("");
            txtNumero.setEnabled(true);
            txtNombre.setEnabled(true);
            txtRepresentante.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtSitio_referencia_not.setEnabled(true);
            txtTelefono.setEnabled(true);
            btneliminar.setVisible(false);
            btnmodificar.setVisible(false);
            break;
            case "Consulta Especifica":
            txtNumero.setEnabled(true);
            txtNombre.setText("");
            txtRepresentante.setText("");
            txtDireccion.setText("");
            txtSitio_referencia_not.setText("");
            txtTelefono.setText("");
            txtNombre.setEnabled(false);
            txtRepresentante.setEnabled(false);
            txtDireccion.setEnabled(false);
            txtSitio_referencia_not.setEnabled(false);
            txtTelefono.setEnabled(false);
            break;
            case "Consulta General":
            txtNombre.setText("");
            txtRepresentante.setText("");
            txtDireccion.setText("");
            txtSitio_referencia_not.setText("");
            txtTelefono.setText("");
            txtNumero.setEnabled(false);
            txtNombre.setEnabled(false);
            txtRepresentante.setEnabled(false);
            txtDireccion.setEnabled(false);
            txtSitio_referencia_not.setEnabled(false);
            txtTelefono.setEnabled(false);
            btneliminar.setVisible(false);
            btnmodificar.setVisible(false);
            break;
            default:
            throw new AssertionError();
        }

    }//GEN-LAST:event_comboActionPerformed

    private void btnrealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizarActionPerformed
        switch (combo.getSelectedItem().toString()) {
            case "Insertar":
            objcrud.insertarNotaria(txtNumero.getText(),txtNombre.getText(), txtRepresentante.getText(), txtDireccion.getText(), txtSitio_referencia_not.getText(), txtTelefono.getText());
            break;
            case "Consulta Especifica":
            btneliminar.setVisible(true);
            btnmodificar.setVisible(true);
            txtNombre.setEnabled(true);
            txtRepresentante.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtSitio_referencia_not.setEnabled(true);
            txtTelefono.setEnabled(true);
            objcrud.consultaIdNotaria(txtNumero.getText());
            txtNumero.setText(var.getId_not());
            txtNombre.setText(var.getNombre_not());
            txtRepresentante.setText(var.getRepresentante_not());
            txtDireccion.setText(var.getCalle_principal_not());
            txtSitio_referencia_not.setText(var.getSitio_referencia_not());
            txtTelefono.setText(var.getTelefono_not());
            break;
            case "Consulta General":
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("Numero");
            modelo.addColumn("Nombres");
            modelo.addColumn("Representantes");
            modelo.addColumn("Direccion");
            modelo.addColumn("Sitio Referencial");
            modelo.addColumn("Telefono");
            tb.setModel(modelo);
            String datos[]= new String[10];
            ConexionPostgreSQL con = new ConexionPostgreSQL();
            try {
                Connection conexion =con.Conectar();
                java.sql.Statement st = conexion.createStatement();
                String sql="select * from notaria";
                ResultSet rs=st.executeQuery(sql);
                while (rs.next())
                {
                    datos[0]=rs.getString("id_not");
                    datos[1]=rs.getString("nombre_not");
                    datos[2]=rs.getString("representante_not");
                    datos[3]=rs.getString("calle_principal_not");
                    datos[4]=rs.getString("sitio_referencia_not");
                    datos[5]=rs.getString("telefono_not");
                    modelo.addRow(datos);
                    
                }
                rs.close();
                conexion.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el sistema de busqueda","Error buscqueda",JOptionPane.ERROR_MESSAGE);
            }
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_btnrealizarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        CrudSQL objcrud=new CrudSQL();
        Variables var=new Variables();
        var.setId_not(txtNumero.getText());
        var.setNombre_not(txtNombre.getText());
        var.setRepresentante_not(txtRepresentante.getText());
        var.setCalle_principal_not(txtDireccion.getText());
        var.setSitio_referencia_not(txtSitio_referencia_not.getText());
        var.setTelefono_not(txtTelefono.getText());
        objcrud.modificarNotaria(var.getId_not(), var.getNombre_not(), var.getRepresentante_not(), var.getCalle_principal_not(), var.getSitio_referencia_not(), var.getTelefono_not());
        txtNumero.setEnabled(true);
        txtNombre.setText("");
        txtRepresentante.setText("");
        txtDireccion.setText("");
        txtSitio_referencia_not.setText("");
        txtTelefono.setText("");
        txtNombre.setEnabled(false);
        txtRepresentante.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtSitio_referencia_not.setEnabled(false);
        txtTelefono.setEnabled(false);
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        CrudSQL objcrud=new CrudSQL();
        Variables var=new Variables();
        objcrud.eliminarNotaria(var.getId_not());
        txtNumero.setEnabled(true);
        txtNombre.setText("");
        txtRepresentante.setText("");
        txtDireccion.setText("");
        txtSitio_referencia_not.setText("");
        txtTelefono.setText("");
        
        
        txtNombre.setEnabled(false);
        txtRepresentante.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtSitio_referencia_not.setEnabled(false);
        txtTelefono.setEnabled(false);
        btneliminar.setVisible(false);
        btnmodificar.setVisible(false);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtSitio_referencia_notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSitio_referencia_notActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSitio_referencia_notActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Notaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Notaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Notaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Notaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Notaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnrealizar;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtSitio_referencia_not;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
