/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastral_system;

import SQL.ConexionPostgreSQL;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author VzWhite
 */
public class TransactionTwo extends javax.swing.JFrame {

    /**
     * Creates new form TransactionTwo
     */
    public TransactionTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtFechainicial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnconsulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtFechafinal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btntransaccional = new javax.swing.JButton();
        txtIdfecha = new javax.swing.JTextField();
        txtFechasolicitud = new javax.swing.JTextField();
        btnnotransaccional = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("TRANSACTION TWO");

        jLabel1.setText("Id Fecha:");

        btnconsulta.setText("Consultar Solicitudes");
        btnconsulta.setToolTipText("");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha solicitud:");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb);

        jButton2.setText("Consultar Fechas de solicitudes");
        jButton2.setActionCommand("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha final:");

        jLabel3.setText("Fecha inicial:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Transaccion fecha y solicitud");

        btntransaccional.setText("Realizar (transaccional)");
        btntransaccional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaccionalActionPerformed(evt);
            }
        });

        txtIdfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdfechaActionPerformed(evt);
            }
        });

        btnnotransaccional.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnnotransaccional.setText("Realizar (No transaccional)");
        btnnotransaccional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotransaccionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(260, 260, 260))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(390, 400, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechainicial, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtIdfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechasolicitud))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(36, 36, 36)
                                .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btntransaccional, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnnotransaccional)
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnconsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFechasolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btntransaccional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnotransaccional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Id solicitud");
        modelo.addColumn("Id catastral");
        modelo.addColumn("Id servicio");
        modelo.addColumn("Id propietario");
        modelo.addColumn("id tecnico");
        modelo.addColumn("Estado");
        modelo.addColumn("Id fecha");
        modelo.addColumn("Id descripción");
        modelo.addColumn("Monto");

        tb.setModel(modelo);
        String datos[]= new String[10];
        ConexionPostgreSQL con = new ConexionPostgreSQL();
        try {
            Connection conexion =con.Conectar();
            java.sql.Statement st = conexion.createStatement();
            String sql="select * from solicitud order by id_solicitud asc";
            ResultSet rs=st.executeQuery(sql);
            while (rs.next())
            {
                datos[0]=rs.getString("id_solicitud");
                datos[1]=rs.getString("id_catastral");
                datos[2]=rs.getString("id_serv_tecnico");
                datos[3]=rs.getString("id_propietario");
                datos[4]=rs.getString("id_tecnico");
                datos[5]=rs.getString("estado_solicitud");
                datos[6]=rs.getString("id_fecha");
                datos[7]=rs.getString("id_descripcion");
                datos[8]=rs.getString("monto_pagar");

                modelo.addRow(datos);
            }
            rs.close();
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el sistema de busqueda","Error buscqueda",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnconsultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Index abrir= new Index();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Id fecha");
        modelo.addColumn("Fecha solicitud");
        modelo.addColumn("Fecha inicio");
        modelo.addColumn("Fecha final");
        tb.setModel(modelo);
        String datos[]= new String[5];
        ConexionPostgreSQL con = new ConexionPostgreSQL();
        try {
            Connection conexion =con.Conectar();
            java.sql.Statement st = conexion.createStatement();
            String sql="select * from fecha_solicitud order by id_fecha asc";
            ResultSet rs=st.executeQuery(sql);
            while (rs.next())
            {
                datos[0]=rs.getString("id_fecha");
                datos[1]=rs.getString("fecha_solicitud");
                datos[2]=rs.getString("fecha_inicio");
                datos[3]=rs.getString("fecha_final");

                modelo.addRow(datos);
            }
            rs.close();
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el sistema de busqueda: "+e,"Error buscqueda",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btntransaccionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaccionalActionPerformed
        ConexionPostgreSQL con = new ConexionPostgreSQL();
        CallableStatement cs;
        try {
            Connection conexion =con.Conectar();
            cs=conexion.prepareCall("call transactionTwo(?,?,?,?)");
            SimpleDateFormat formato=new SimpleDateFormat("yyyy/MM/dd");
            
            cs.setInt(1,Integer.parseInt(txtIdfecha.getText()));
            
            if("".equals(txtFechasolicitud.getText())){
                cs.setDate(2, null);
            }else{
                Date fecha=formato.parse(txtFechasolicitud.getText());
                java.sql.Date date=new java.sql.Date(fecha.getTime());
                cs.setDate(2, date);
            }
            
            if("".equals(txtFechainicial.getText())){
                cs.setDate(3, null);
            }else{
                Date fecha2 = formato.parse(txtFechainicial.getText());
                java.sql.Date date2 = new java.sql.Date(fecha2.getTime());
                cs.setDate(3, date2);
            }
            
            
            if("".equals(txtFechafinal.getText())){
                cs.setDate(4, null);
            }else{
                Date fecha3 = formato.parse(txtFechafinal.getText());
                java.sql.Date date3 = new java.sql.Date(fecha3.getTime());
                cs.setDate(4, date3);
            }
                        

            cs.execute();
            cs.close();
            conexion.close();
            JOptionPane.showMessageDialog(null, "¡Transaccion faliida!", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Transaccion ejecutada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btntransaccionalActionPerformed

    private void txtIdfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdfechaActionPerformed

    private void btnnotransaccionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotransaccionalActionPerformed
        ConexionPostgreSQL con = new ConexionPostgreSQL();
        CallableStatement cs;
        try {
            Connection conexion =con.Conectar();
            cs=conexion.prepareCall("call transactionTwoFail(?,?,?,?)");
            SimpleDateFormat formato=new SimpleDateFormat("yyyy/MM/dd");
            
            cs.setInt(1,Integer.parseInt(txtIdfecha.getText()));
            
            if("".equals(txtFechasolicitud.getText())){
                cs.setDate(2, null);
            }else{
                Date fecha=formato.parse(txtFechasolicitud.getText());
                java.sql.Date date=new java.sql.Date(fecha.getTime());
                cs.setDate(2, date);
            }
            
            if("".equals(txtFechainicial.getText())){
                cs.setDate(3, null);
            }else{
                Date fecha2 = formato.parse(txtFechainicial.getText());
                java.sql.Date date2 = new java.sql.Date(fecha2.getTime());
                cs.setDate(3, date2);
            }
            
            
            if(txtFechafinal.getText() != null ){
                cs.setDate(4, null);
            }else{
                Date fecha3 = formato.parse(txtFechafinal.getText());
                java.sql.Date date3 = new java.sql.Date(fecha3.getTime());
                cs.setDate(4, date3);
            }

            cs.execute();
            cs.close();
            conexion.close();
            JOptionPane.showMessageDialog(null, "¡Transaccion faliida!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnnotransaccionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnnotransaccional;
    private javax.swing.JButton btntransaccional;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtFechafinal;
    private javax.swing.JTextField txtFechainicial;
    private javax.swing.JTextField txtFechasolicitud;
    private javax.swing.JTextField txtIdfecha;
    // End of variables declaration//GEN-END:variables
}
